### ISSUE TITLE
LSP go to definition includes top frontmatter fences in Telescope results

### ISSUE THREAD

**Issue by tjex** [zk-org/zk-nvim#185]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Being tracked at https://github.com/zk-org/zk/issues/447. But also worth posting here. 
It's not immediately clear if its a zk-nvim issue or zk lsp issue.

### How to reproduce?

see above issue link

### zk configuration

```toml
na
```

### Neovim configuration

```viml
na
```

### Environment

```bash
zk 0.14.1-12-g0787930
system: Darwin 23.6.0 arm64
NVIM v0.10.0
Build type: Debug
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by tjex** [comment]
The problem was that I needed to also set my keymap for go to definition in zk conf. I only had it set in lsp conf. 

Both marksman and zk were reporting back with results for go to definition. But for some reason, when zk didn't have the same keybind set in its `on_attach` table, the two different results (masons being the heading of the file, and zk's being the first line of the file) would be returned as multiple results, and so Telescope / fzf_lua were being used as my list picker to see which I wanted to go to.

I don't know why now I don't get any multi-select list being presented to me, just because I have the keybind set in zk conf 🤷‍♂️

```lua
lsp = {
    config = {
        cmd = { "zk", "lsp", "--log", "/tmp/zk-lsp.log" },
        name = "zk",
        on_attach = function()
            require("cmp_nvim_lsp").default_capabilities()
            key.nmap({ "gd", vim.lsp.buf.definition })
            keymaps()
        end,
    },

```

**Comment by winter-again** [comment]
I use `zk-nvim` with `marksman` and `fzf-lua` for handling go to definition. Both servers were sending back definition results, meaning `fzf-lua` is forced to display both instead of instantly jumping to the note (like the issue described above). I fixed by by simply setting `definitionProvider` to `false`:

```lua
require("zk").setup({
    picker = "fzf_lua",
    lsp = {
        config = {
            cmd = { "zk", "lsp" },
            name = "zk",
            on_attach = function(client, bufnr)
                -- NOTE: disable to avoid sending another request alongside marksman
                client.server_capabilities.definitionProvider = false
            end,
        },
    },
    auto_attach = {
        enabled = true,
        filetypes = { "markdown" },
    },
})
```
