### ISSUE TITLE
Error when calling ZkInsertLinkAtSelection

### ISSUE THREAD

**Issue by nathanbraun** [zk-org/zk-nvim#198]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I have this keybinding set up in my lua config.

```
  vim.keymap.set("v", "[[n", ":'<,'>ZkInsertLinkAtSelection<CR>", opts)
```

How it worked before is I would select some text in visual mode, press `[[n`, and my note picker would pop up (I had other versions of the command, e.g. `[[x` that would filter the notes depending on what I was looking for). Then I could pick the note, and it'd insert a link to it where the title was what I selected.

However now when I do that I get this error:

```
Error executing Lua callback: vim/_editor.lua:0: bad argument #1 to 'min' (number expected, got nil)
stack traceback:
        [C]: in function 'min'
        vim/_editor.lua: in function 'region'
        ...thanbraun/.local/share/nvim/lazy/zk-nvim/lua/zk/util.lua:98: in function 'get_selected_text'
        ...ocal/share/nvim/lazy/zk-nvim/lua/zk/commands/builtin.lua:78: in function 'insert_link'
        ...ocal/share/nvim/lazy/zk-nvim/lua/zk/commands/builtin.lua:109: in function 'fn'
        .../.local/share/nvim/lazy/zk-nvim/lua/zk/commands/init.lua:19: in function <.../.local/share/nvim/lazy/zk-nvim/lua/zk/commands/init.lua:12>
```

### How to reproduce?

1. Select some text.
2. Run `:'<,'>ZkInsertLinkAtSelection`

### zk configuration

```toml
default
```

### Neovim configuration

```viml
local opts = { noremap = true, silent = true}
  vim.keymap.set("v", "[[n", ":'<,'>ZkInsertLinkAtSelection<CR>", opts)
```

### Environment

```bash
❯ zk --version && echo "system: `uname -srmo`" && nvim --version
zk HEAD-b3d88df
system: Darwin 24.1.0 arm64
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"
```

**Comment by tjex** [comment]
This keybind may be getting confused with the builtin completion trigger, which is `[[`.

Have you tried changing the keybind to something standard, like `<leader>zi`?

**Comment by nathanbraun** [comment]
> @nathanbraun maybe try updating your Neovim?

Yep, this took care of it.  Thanks for figuring it out @KarlNaumann!

**Comment by tjex** [comment]
Was coming on with the same results, but it should be that 9.5 should work fine...
