### ISSUE TITLE
Is there a way to exclude notes with the built-in pickers?

### ISSUE THREAD

**Issue by nathanbraun** [zk-org/zk-nvim#199]
Currently I have this command to open notes with tag "project":

```
  vim.keymap.set("n", "<leader>zopr", '<Cmd>ZkNotes { tags = {"project"}, sort = {"modified"}}<CR>', opts)
```

What I'd like to do is modify it to exclude notes that are also tagged "archived".  It looks like the underlying zk program has an exclude command.  I tried:

```
  vim.keymap.set("n", "<leader>zopr", '<Cmd>ZkNotes { tags = {"project"}, sort = {"modified"}, exclude = {tags = "archived"}}<CR>', opts)
```

But it didn't seem to work -- any idea if this is possible?

**Comment by tjex** [comment]
As far as I understand, no. You can only exclude by file path, which is under `excludeHrefs`.

**Comment by tjex** [comment]
@nathanbraun 
So I think you could build this into a function pretty easily. Look at the api section of the docs. You could use `zk.list` to return notes that _match_ a tag passesd as an argument (e.g `project`) and then use the resulting table of file paths with a call to `ZkNotes { excludeHrefs = project_notes }`.
