### ISSUE TITLE
Support backlinks in frontmatter

### ISSUE THREAD

**Issue by alancunha26** [zk-org/zk-nvim#201]
I'm migrating to ZK and have a lot of notes with links under the frontmatter, the navigation works as intended, but the ZkBacklinks of the nvim plugin don't list this links.

```yaml
links:
  - "[[file|alias]]"
  - "[alias](link)"
```

I found an [issue](https://github.com/zk-org/zk/issues/321#issuecomment-2525474638) on the zk main project related to this.

**Comment by tjex** [comment]
Great that you're migrating over here :)  
Unfortunately, this isn't something I would be looking to support (edit: see below, things change). Links in frontmatter is a very large divergence from what frontmatter is intended for, metadata.  

There are other more pressing issues and interesting features that should be implemented first. 

As a half way solution, you could just move that links section down to the "footer" of every note, maybe under a line separtor `---`. Then `:ZkBacklinks` will work.

eg.

```markdown
---
frontmatter:
---

# h1

body

---

links:
    - link1
    - link2

<EOF>
```

**Comment by tjex** [comment]
@alancunha26 This is now supported :)
